#include<stdio.h>
#define m 1000
int main (void)
{
    unsigned long long n[m];
    int i=0;
    while((scanf("%llu",&n[0])) !=EOF)
    {
        i=0;
        printf("Hailstone generated by %llu:\n",n[0]);
        while(n[i]!=1)
        {
            if(n[i]%2==0)
        {
            n[i+1]=n[i]/2;
            printf("%llu ",n[i]);
            i++;
        }
        else if (n[i]%2==1)
        {
            n[i+1]=3*n[i]+1;
            printf("%llu ",n[i]);
            i++;
        }
        }
    printf("1\nNumber of hailstone generated:%d\n\n",i+1);
    }

    return 0;
}
